import "./globals.css";

import Header from "./components/navigation/Header";
import Head from "next/head";
import Menu from "./components/navigation/Menu";
import Footer from "./components/navigation/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <Head>
        <link rel="icon" href="/favicon.svg" />
      </Head> */}
      <body className="bg-background">
        <Header />
        {/* <Menu /> */}
        {/* <Navbar></Navbar> */}

        {children}
        <Footer />
      </body>
    </html>
  );
}
