import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./components/navigation/Header";

import Footer from "./components/navigation/Footer";
// import ApiContext from "./lib/ApiContext";
export const metadata = {
  title: "foofest",
  description: "Generated by create next app",
};
const inter = Inter({
  subsets: ["latin"],

  display: "swap",
  variable: "--font-inter",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.variable}>
      <body className="bg-background font-sans ">
        <Header />

        {children}
        <Footer />
      </body>
    </html>
  );
}
